apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dtsse-services
  description: DTS Software Engineering service
  annotations:
    jenkins.io/job-full-name: cft:HMCTS_d_to_i/dtsse-services
    github.com/project-slug: hmcts/dtsse-services
  tags:
    - java
    - postgresql
  links:
    - url: https://hmcts-reform.slack.com/app_redirect?channel=reform-swe
      title: DTS Software Engineering on Slack
      icon: chat
spec:
  type: service
  system: dtsse
  lifecycle: experimental
  owner: rse
